# Generated by Django 5.2.4 on 2025-07-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_voting', '0002_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='result',
            name='votes',
            field=models.IntegerField(),
        ),
    ]
