# Generated by Django 5.2.4 on 2025-07-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_voting', '0005_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('public', 'Public'), ('politician', 'Politician'), ('admin', 'Admin')], max_length=20),
        ),
    ]
