# Generated by Django 5.2.4 on 2025-08-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_voting', '0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='party',
            field=models.CharField(blank=True, choices=[('A', 'Party A'), ('B', 'Party B'), ('C', 'Party C')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('public', 'Public'), ('politician', 'Politician')], max_length=20),
        ),
    ]
