# Generated by Django 5.2.4 on 2025-08-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_voting', '0007_userprofile_party_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='politician_images/'),
        ),
    ]
