# Generated by Django 5.2.4 on 2025-08-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_voting', '0008_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='voter_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
