# Generated by Django 5.2.4 on 2025-08-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_voting', '0009_userprofile_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='voter_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
